### ISSUE TITLE
Problem installing: npm-debug attached

### ISSUE THREAD

**Issue by cmorrow** [bgag/any-db-jdbc#1]
I can't install the plugin. Are there any requirements of Java or di I need to sudo the install command?

[npm-debug.txt](https://github.com/bgag/any-db-jdbc/files/338047/npm-debug.txt)

**Comment by bergos** [comment]
The package depends on `jdbc` and that package depends on `java`. That package causes the error. `node-gyp` is used to compile native code. I think it's a problem with the JDK. First make sure you are using the JDK and not just the JRE. Than have a look at the [README of the java package](https://www.npmjs.com/package/java). There are a lot of hints for the installation for different platforms.

**Comment by cmorrow** [comment]
I use javac -version and get
`javac 1.6.0_65` 
I am running Mac El Capitan

also:
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    1.6.0_65-b14-468, x86_64:   "Java SE 6" /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-468, i386: "Java SE 6" /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

**Comment by bergos** [comment]
I don't know what exactly causes the error, but it's in the `java` package. Can you forward the npm log of `npm install java` to the [java package](https://github.com/joeferner/node-java/issues)?

**Comment by cmorrow** [comment]
npm install java npm-debug.log attached
[npm-debug.txt](https://github.com/bgag/any-db-jdbc/files/339285/npm-debug.txt)

**Comment by cmorrow** [comment]
HI just found out I was running Java 1.6. Upgraded to 1.8 and everything worked perfectly. Sorry.. Can't believe I missed that requirement right in front of my face. I wish the error messages would have stated unsupported Java version.
